### ISSUE TITLE
RuntimeError: The default implementation of __deepcopy__() for non-wrapper subclasses only works for subclass types that implement new_empty() and for which that function returns another instance of the same subclass.

### ISSUE THREAD

**Issue by htnha** [ganji15/HiGANplus#6]
I got this error, please help!

Traceback (most recent call last):
  File "C:\Users\hoang\Dropbox\AI\Handwriting\HiGANplus\train.py", line 25, in <module>
    model.train()
  File "C:\Users\hoang\Dropbox\AI\Handwriting\HiGANplus\networks\model.py", line 718, in train
    self.y.sample_()
  File "C:\Users\hoang\Dropbox\AI\Handwriting\HiGANplus\networks\rand_dist.py", line 63, in sample_
    return deepcopy(self).detach()
  File "C:\Users\hoang\AppData\Local\Programs\Python\Python39\lib\copy.py", line 153, in deepcopy
    y = copier(memo)
  File "C:\Users\hoang\Dropbox\AI\Handwriting\HiGANplus\win-env\lib\site-packages\torch\_tensor.py", line 84, in __deepcopy__
    return handle_torch_function(Tensor.__deepcopy__, (self,), self, memo)
  File "C:\Users\hoang\Dropbox\AI\Handwriting\HiGANplus\win-env\lib\site-packages\torch\overrides.py", line 1551, in handle_torch_function
    result = torch_func_method(public_api, types, args, kwargs)
  File "C:\Users\hoang\Dropbox\AI\Handwriting\HiGANplus\win-env\lib\site-packages\torch\_tensor.py", line 1295, in __torch_function__
    ret = func(*args, **kwargs)
  File "C:\Users\hoang\Dropbox\AI\Handwriting\HiGANplus\win-env\lib\site-packages\torch\_tensor.py", line 170, in __deepcopy__
    raise RuntimeError(
RuntimeError: The default implementation of __deepcopy__() for non-wrapper subclasses only works for subclass types that implement new_empty() and for which that function returns another instance of the same subclass. You should either properly implement new_empty() for your subclass or override __deepcopy__() if it is intended behavior for new_empty() to return an instance of a different type.

**Comment by ganji15** [comment]
Hi, @htnha 

The code is only tested on PyTorch 1.11.0, and newer versions may not be supported.

**Comment by nek0peko** [comment]
Add lines below in network/rand_dist.py may solve your problem:
`
def new_empty(self, *args, **kwargs):
        return self.__class__(*args, **kwargs)

def __deepcopy__(self, memo):
        new_instance = self.new_empty(self.size())
        new_instance.copy_(self)
        return new_instance.detach()
`

**Comment by nek0peko** [comment]
Add lines below in network/rand_dist.py may solve your problem @htnha :
```python
def new_empty(self, *args, **kwargs):
    return self.class(*args, **kwargs)

def deepcopy(self, memo):
    new_instance = self.new_empty(self.size())
    new_instance.copy_(self)
    return new_instance.detach()
```

**Comment by caigun** [comment]
The same issue, and @nek0peko 's method doesn't help (looks like changed the datatype)
running with PyTorch 1.11.0

Traceback (most recent call last):
  File "train.py", line 25, in <module>
    model.train()
  File "/dir/HiGANplus/HiGAN+/networks/model.py", line 726, in train
    self.y.sample_()
  File "/dir/HiGANplus/HiGAN+/networks/rand_dist.py", line 61, in sample_
    return deepcopy(self).detach()
  File "/home/pai/envs/higan/lib/python3.7/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/home/pai/envs/higan/lib/python3.7/site-packages/torch/_tensor.py", line 87, in __deepcopy__
    return handle_torch_function(Tensor.__deepcopy__, (self,), self, memo)
  File "/home/pai/envs/higan/lib/python3.7/site-packages/torch/overrides.py", line 1498, in handle_torch_function
    result = torch_func_method(public_api, types, args, kwargs)
  File "/home/pai/envs/higan/lib/python3.7/site-packages/torch/_tensor.py", line 1121, in __torch_function__
    ret = func(*args, **kwargs)
  File "/home/pai/envs/higan/lib/python3.7/site-packages/torch/_tensor.py", line 149, in __deepcopy__
    new_tensor.set_(new_storage, self.storage_offset(), self.size(), self.stride())
RuntimeError: Expected a Storage of type float or an _UntypedStorage, but got type Long for argument 1 'storage'

**Comment by magistermilitum** [comment]
You must change the line in ./networks/rand_dist.py:
`return deepcopy(self).detach()`
by
`return torch.clone(self).detach()`
